/**
 * Textes de l interface, dans chaque langue proposee. Le francais est la reference ; l anglais est
 * relu ; le wolof et le pulaar sont une premiere version (brouillon d un modele de langage, relu et
 * corrige) a faire valider par des locuteurs. Variables : {query}, {title}, {page}.
 */
import type { Lang } from "./languages";

const FR = {
  assistant: "Assistant de l'ANSD",
  tagline: "Statistiques — ANSD",
  newChat: "Nouvelle discussion",
  toggleHistory: "Afficher ou masquer l'historique des discussions",
  history: "Historique des discussions",
  closeHistory: "Fermer l'historique",
  searchChats: "Rechercher une discussion",
  clearSearch: "Effacer la recherche",
  noMatch: "Aucune discussion ne correspond à « {query} ».",
  renameHint: "{title} — double-clic pour renommer",
  rename: "Renommer",
  renameChat: "Renommer la discussion « {title} »",
  newTitle: "Nouveau titre de la discussion",
  delete: "Supprimer",
  deleteChat: "Supprimer la discussion « {title} »",
  confirmDelete: "Supprimer la discussion « {title} » ?",
  today: "Aujourd'hui",
  yesterday: "Hier",
  last7Days: "7 derniers jours",
  older: "Plus ancien",
  language: "Langue",
  chooseLanguage: "Choisir la langue",
  listening: "Je vous écoute…",
  stopDictation: "Arrêter la dictée",
  dictate: "Dicter la question au microphone",
  send: "Envoyer la question",
  stopAndSend: "Arrêter et envoyer la question",
  speakQuestion: "Poser ma question à voix haute",
  listeningTap: "Je vous écoute… touchez pour envoyer",
  tapToSpeak: "Touchez pour parler",
  writeInstead: "Écrire plutôt",
  yourRecording: "Votre enregistrement",
  transcribing: "Transcription en cours…",
  searching: "Recherche en cours dans les publications de l'ANSD",
  askAgain: "Reposer la question",
  details: "Explication détaillée",
  listen: "Réponse audio",
  listenLabel: "Écouter la réponse en audio",
  preparing: "Préparation…",
  pause: "Pause",
  resume: "Reprendre",
  cancel: "Annuler",
  regenerate: "Relancer la question",
  regenerateLabel: "Relancer la question pour obtenir une nouvelle réponse",
  copy: "Copier",
  copyAnswer: "Copier la réponse",
  copied: "Copié",
  copyFailed: "Échec de la copie",
  copyDetails: "Copier l'explication",
  close: "Fermer",
  retry: "Réessayer",
  sources: "Sources",
  page: "page",
  openSource: "Ouvrir « {title} »",
  openSourcePage: "Ouvrir « {title} » à la page {page}",
  originalFrench: "Voir le texte original en français",
  voiceChatTitle: "Question vocale",
  genericError: "Un bug est survenu. Veuillez réessayer.",
  voiceInputUnavailable: "La question à voix haute n'est pas encore disponible dans cette langue ou sur ce navigateur. Utilisez Chrome, Edge ou Safari, en français ou en anglais.",
  micDenied: "Accès au micro refusé. Autorisez le micro dans les réglages du navigateur pour poser votre question à voix haute.",
  noSpeech: "Aucune parole détectée — parlez plus près du micro et réessayez.",
  needInternet: "La reconnaissance vocale nécessite une connexion Internet.",
  micUnavailable: "Le micro n'est pas accessible depuis ce navigateur.",
  noSound: "Aucun son enregistré — réessayez.",
  playbackUnavailable: "La lecture audio n'est pas encore disponible dans cette langue.",
};

export type UiKey = keyof typeof FR;
type UiTexts = Record<UiKey, string>;

const EN: UiTexts = {
  assistant: "ANSD Assistant",
  tagline: "Statistics — ANSD",
  newChat: "New conversation",
  toggleHistory: "Show or hide conversation history",
  history: "Conversation history",
  closeHistory: "Close history",
  searchChats: "Search conversations",
  clearSearch: "Clear search",
  noMatch: "No conversation matches “{query}”.",
  renameHint: "{title} — double-click to rename",
  rename: "Rename",
  renameChat: "Rename conversation “{title}”",
  newTitle: "New conversation title",
  delete: "Delete",
  deleteChat: "Delete conversation “{title}”",
  confirmDelete: "Delete conversation “{title}”?",
  today: "Today",
  yesterday: "Yesterday",
  last7Days: "Last 7 days",
  older: "Older",
  language: "Language",
  chooseLanguage: "Choose language",
  listening: "Listening…",
  stopDictation: "Stop dictation",
  dictate: "Dictate the question",
  send: "Send the question",
  stopAndSend: "Stop and send the question",
  speakQuestion: "Ask my question out loud",
  listeningTap: "Listening… tap to send",
  tapToSpeak: "Tap to speak",
  writeInstead: "Type instead",
  yourRecording: "Your recording",
  transcribing: "Transcribing…",
  searching: "Searching ANSD publications",
  askAgain: "Ask again",
  details: "Detailed explanation",
  listen: "Audio answer",
  listenLabel: "Listen to the answer",
  preparing: "Preparing…",
  pause: "Pause",
  resume: "Resume",
  cancel: "Cancel",
  regenerate: "Regenerate",
  regenerateLabel: "Ask again to get a new answer",
  copy: "Copy",
  copyAnswer: "Copy the answer",
  copied: "Copied",
  copyFailed: "Copy failed",
  copyDetails: "Copy the explanation",
  close: "Close",
  retry: "Try again",
  sources: "Sources",
  page: "page",
  openSource: "Open “{title}”",
  openSourcePage: "Open “{title}” at page {page}",
  originalFrench: "See the original French text",
  voiceChatTitle: "Voice question",
  genericError: "Something went wrong. Please try again.",
  voiceInputUnavailable: "Voice questions are not yet available in this language or browser. Use Chrome, Edge or Safari, in French or English.",
  micDenied: "Microphone access denied. Allow the microphone in your browser settings to ask your question out loud.",
  noSpeech: "No speech detected — speak closer to the microphone and try again.",
  needInternet: "Speech recognition requires an Internet connection.",
  micUnavailable: "The microphone is not available in this browser.",
  noSound: "Nothing was recorded — try again.",
  playbackUnavailable: "Audio playback is not yet available in this language.",
};

const WO: UiTexts = {
  assistant: "Dimbalikatu ANSD",
  tagline: "Statistiques — ANSD",
  newChat: "Waxtaan bu bees",
  toggleHistory: "Wone walla nëbb taariixu waxtaan yi",
  history: "Taariixu waxtaan yi",
  closeHistory: "Tëj taariix bi",
  searchChats: "Seet waxtaan",
  clearSearch: "Far seet gi",
  noMatch: "Amul benn waxtaan bu dëppoo ak « {query} ».",
  renameHint: "{title} — bësal ñaari yoon ngir soppi tur bi",
  rename: "Soppi tur bi",
  renameChat: "Soppi turu waxtaan bi « {title} »",
  newTitle: "Tur bu bees ngir waxtaan bi",
  delete: "Far",
  deleteChat: "Far waxtaan bi « {title} »",
  confirmDelete: "Ndax nga bëgg a far waxtaan bi « {title} » ?",
  today: "Tey",
  yesterday: "Démb",
  last7Days: "7 fan yi weesu",
  older: "Bu yàgg",
  language: "Làkk",
  chooseLanguage: "Tànn làkk bi",
  listening: "Maa ngi déglu…",
  stopDictation: "Taxawal wax gi",
  dictate: "Wax laaj bi ci micro bi",
  send: "Yónnee laaj bi",
  stopAndSend: "Taxawal te yónnee laaj bi",
  speakQuestion: "Laaj sa laaj ci kàddu",
  listeningTap: "Maa ngi déglu… tëgg ngir yónnee",
  tapToSpeak: "Tëgg ngir wax",
  writeInstead: "Bind ko",
  yourRecording: "Li nga wax",
  transcribing: "Maa ngi bind li nga wax…",
  searching: "Maa ngi seet ci kayiti ANSD yi",
  askAgain: "Laajaat",
  details: "Leeral bu yaatu",
  listen: "Tontu ci kàddu",
  listenLabel: "Déglu tontu bi ci kàddu",
  preparing: "Maa ngi koy waajal…",
  pause: "Taxawal",
  resume: "Wéyal",
  cancel: "Bàyyi",
  regenerate: "Laajaat",
  regenerateLabel: "Laajaat ngir am tontu bu bees",
  copy: "Duppi",
  copyAnswer: "Duppi tontu bi",
  copied: "Duppi nañu ko",
  copyFailed: "Duppi gi antuwul",
  copyDetails: "Duppi leeral bi",
  close: "Tëj",
  retry: "Jéemaatal",
  sources: "Sources",
  page: "page",
  openSource: "Ubbil « {title} »",
  openSourcePage: "Ubbil « {title} » ci page {page}",
  originalFrench: "Gis mbind mi ci farañse",
  voiceChatTitle: "Laaj ci kàddu",
  genericError: "Am na njuumte. Jéemaatal.",
  voiceInputUnavailable: "Laaj ci kàddu amagul ci làkk bii walla ci navigateur bii. Jëfandikool Chrome, Edge walla Safari, ci farañse walla ci àngale.",
  micDenied: "Mayuñu micro bi. May ko ci réglages yu navigateur bi ngir mën a laaj ci kàddu.",
  noSpeech: "Dégguñu benn kàddu — wax ci wetu micro bi te jéemaatal.",
  needInternet: "Dégg kàddu gi laaj na Internet.",
  micUnavailable: "Micro bi mënul a dox ci navigateur bii.",
  noSound: "Amul benn kàddu bu ñu denc — jéemaatal.",
  playbackUnavailable: "Déglu tontu bi ci kàddu amagul ci làkk bii.",
};

const FF: UiTexts = {
  assistant: "Ballal ANSD",
  tagline: "Statistik — ANSD",
  newChat: "Haala hesere",
  toggleHistory: "Holla walla suuɗo daartol haalaaji",
  history: "Daartol haalaaji",
  closeHistory: "Uddu daartol",
  searchChats: "Yiylo haala",
  clearSearch: "Momtu yiylo",
  noMatch: "Alaa haala nannduɗo e « {query} ».",
  renameHint: "{title} — fiyo laabi ɗiɗi ngam waylude innde",
  rename: "Waylu innde",
  renameChat: "Waylu innde haala « {title} »",
  newTitle: "Innde hesere haala",
  delete: "Momtu",
  deleteChat: "Momtu haala « {title} »",
  confirmDelete: "Aɗa yiɗi momtude haala « {title} » ?",
  today: "Hannde",
  yesterday: "Hanki",
  last7Days: "Balɗe 7 sakkitiije",
  older: "Ko ɓooyi",
  language: "Ɗemngal",
  chooseLanguage: "Suɓo ɗemngal",
  listening: "Miɗo nanee ma…",
  stopDictation: "Haaytu winndugol daande",
  dictate: "Winndu naamndal ngal e mikro",
  send: "Nulda naamndal ngal",
  stopAndSend: "Haaytu e nulda naamndal ngal",
  speakQuestion: "Naamno e daande",
  listeningTap: "Miɗo nanee ma… fiyo ngam nuldude",
  tapToSpeak: "Fiyo ngam haalude",
  writeInstead: "Winndu ko ɓuri ɗum",
  yourRecording: "Winndannde maa",
  transcribing: "Miɗo winnda daande ndee…",
  searching: "Miɗo yiylo e binndanɗe ANSD",
  askAgain: "Naamndo kadi",
  details: "Sifaa timmuɗo",
  listen: "Jaabawol daande",
  listenLabel: "Heɗo jaabawol ngol e daande",
  preparing: "Miɗo moofta…",
  pause: "Darana",
  resume: "Fuɗɗo kadi",
  cancel: "Haaytu",
  regenerate: "Naamndo kadi",
  regenerateLabel: "Naamndo kadi ngam heɓde jaabawol kesol",
  copy: "Kopi",
  copyAnswer: "Kopi jaabawol ngol",
  copied: "Kopiima",
  copyFailed: "Kopi ngol roŋkii",
  copyDetails: "Kopi firo ngo",
  close: "Uddu",
  retry: "Eto kadi",
  sources: "Sources",
  page: "page",
  openSource: "Maɓɓit « {title} »",
  openSourcePage: "Maɓɓit « {title} » e page {page}",
  originalFrench: "Ndaaro binndol asliwol e Farayse",
  voiceChatTitle: "Naamndal daande",
  genericError: "Juumre waɗii. Eto kadi.",
  voiceInputUnavailable: "Naamndal e daande alaa tawo e ɗemngal ngal walla e navigateur oo. Huutoro Chrome, Edge walla Safari, e Farayse walla e Engele.",
  micDenied: "Jaɓɓugol mikro ngol salaama. Jaɓɓo mikro ngol e toɓɓe njuɓɓudi ngam naamndude e daande.",
  noSpeech: "Alaa haala nanaaɗo — haaldu ɓadda mikro ngol, eto kadi.",
  needInternet: "Anndugol daande ina haani jokkondiral Internet.",
  micUnavailable: "Mikro ngol heɓaaka e navigateur oo.",
  noSound: "Alaa daande winndaaɗe — eto kadi.",
  playbackUnavailable: "Heɗtugol daande alaa tawo e ɗemngal ngal.",
};

// Sereer et diola : pas encore de traduction, l interface reste en francais.
export const UI_TEXTS: Record<Lang, UiTexts> = { FR, EN, WO, FF, SRR: FR, DYO: FR };
